/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package addUser;
import javax.swing.JOptionPane;

/**
 *
 * @author pardoje_cis21035
 */
public class addUser extends javax.swing.JFrame {

    /**
     * Creates new form addUser
     */
    public addUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FirstName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Birthdate = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        FirstNameTxt = new javax.swing.JTextField();
        LastNameTxt = new javax.swing.JTextField();
        BirthdateTxt = new javax.swing.JTextField();
        AddressTxt = new javax.swing.JTextField();
        EmailTxt = new javax.swing.JTextField();
        ConNumTxt = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        ConNum = new javax.swing.JLabel();
        userPhoto = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();
        SaveInfo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(64, 224, 208));

        FirstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FirstName.setText("First Name");

        LastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LastName.setText("Last Name");

        Birthdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Birthdate.setText("Birthdate");

        Address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Address.setText("Address    ");

    private void LastNameTxtActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void AddressTxtActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void EmailTxtActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void FirstNameTxtActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void BirthdateTxtActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {                                      

        FirstNameTxt.setText("");
        LastNameTxt.setText("");
        BirthdateTxt.setText("");
        AddressTxt.setText("");
        EmailTxt.setText("");
        ConNumTxt.setText("");
    }                                     

    private void ConNumTxtActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void SaveInfoActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String fName = FirstNameTxt.getText();
        String lName = LastNameTxt.getText();
        String birthDate = BirthdateTxt.getText();
        String add = AddressTxt.getText();
        String emel = EmailTxt.getText();
        String con = ConNumTxt.getText();
        if(fName.equals("")){
            JOptionPane.showMessageDialog(null,"First Name is required!");
        }else if(lName.equals("")){
            JOptionPane.showMessageDialog(null,"Last Name is required!");
        }else if(birthDate.equals("")){
            JOptionPane.showMessageDialog(null,"Birthdate is required!");
        }else if(add.equals("")){
            JOptionPane.showMessageDialog(null,"Address is required!");
        }else if(emel.equals("")){
            JOptionPane.showMessageDialog(null,"Email is required!");
        }else if(con.equals("")){
            JOptionPane.showMessageDialog(null,"Contact Number is required!");
        }else{
            JOptionPane.showMessageDialog(null,"Save Success!");
        }
        System.out.println("First Name:"+fName);
        System.out.println("Last Name:"+lName);
        System.out.println("Birthday:"+birthDate);
        System.out.println("Address:"+add);
        System.out.println("Email:"+emel);
        System.out.println("Contact Number:"+con);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Address;
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JLabel Birthdate;
    private javax.swing.JTextField BirthdateTxt;
    private javax.swing.JLabel ConNum;
    private javax.swing.JTextField ConNumTxt;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField FirstNameTxt;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField LastNameTxt;
    private javax.swing.JButton Reset;
    private javax.swing.JButton SaveInfo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel userPhoto;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
